spring:
  application:
   name : ai-serivce

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      database: fitnessrecommendation



server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
